import { Hatchify as HatchifyNode, buildExportWrapper } from "@hatchifyjs/node"
import type {
  HatchifyOptions,
  ModelFunctionsCollection,
  PartialSchema,
} from "@hatchifyjs/node"
import xss from "xss"

import { buildMiddlewareForModel } from "./middleware.js"
import type { MiddlewareFunctionsKoa } from "./middleware.js"

export interface XSSHatchify extends HatchifyNode {
  xssProtection: boolean
  validateXSS(data: any, schema: PartialSchema): void
}

/**
 * Hatchify can be imported from the `@hatchifyjs/koa` package
 *
 * This class provides the entry point into the Hatchify library. To use Hatchify with your project
 * you will create an instance of this class passing it your Model definitions along with (optional) settings.
 *
 * @see {@link constructor}
 *
 * In order to use Hatchify with Koa or Express you should look at the Middleware exports below
 * @see {@link MiddlewareFunctionsKoa.all}
 *
 */
export class Hatchify extends HatchifyNode implements XSSHatchify {
  xssProtection: boolean
  schemas: Record<string, PartialSchema>

  constructor(
    schemas: Record<string, PartialSchema>,
    options: HatchifyOptions = {},
  ) {
    super(schemas, options)
    this.xssProtection = options.xssProtection ?? false
    this.schemas = schemas
  }

  /**
   * Validates input data to prevent XSS attacks by comparing with sanitized version
   * @param data The data to validate
   * @param schema The schema associated with the data
   * @returns true if data is safe, throws error if XSS is detected
   */
  validateXSS(data: any, schema: PartialSchema): void {
    if (!this.xssProtection) {
      return
    }

    if (typeof data === "string") {
      // Check if this field is exempt in the schema
      if (schema.attributes[data]?.control?.xssExempt) {
        return
      }
      const sanitized = xss(data)
      if (data !== sanitized) {
        throw new Error(
          "Potential XSS detected in input. HTML should be escaped.",
        )
      }
    }

    if (Array.isArray(data)) {
      data.forEach((item) => this.validateXSS(item, schema))
    }

    if (data && typeof data === "object") {
      Object.values(data).forEach((value) => this.validateXSS(value, schema))
    }
  }

  /**
   * The `middleware` export is one of the primary tools provided by Hatchify for working
   * with your Models in custom routes.
   *
   * From the `middleware` export you can target one of your Models by name which will
   * give you further access to a number of named functions
   *
   * For more information about the underlying per-model functions:
   * @see {@link MiddlewareFunctionsKoa}
   *
   * @returns {ModelFunctionsCollection<MiddlewareFunctionsKoa>}
   * @category General Use
   */
  get middleware(): ModelFunctionsCollection<MiddlewareFunctionsKoa> {
    return buildExportWrapper<MiddlewareFunctionsKoa>(
      this,
      buildMiddlewareForModel,
    )
  }
}

export { errorHandlerMiddleware } from "./middleware.js"

/**
 * `hatchifyKoa` Creates middleware functions from provided schemas
 * @param schemas An object with partial schemas
 * @param options Customization options like URL prefix, database options, and XSS protection
 * @returns {Hatchify} A Hatchify object with the middleware functions and other autogenerated objects
 */
export function hatchifyKoa(
  schemas: Record<string, PartialSchema>,
  options: HatchifyOptions = {},
): Hatchify {
  return new Hatchify(schemas, options)
}
